export default [
  {
    club_name: "Nigerian Professional Football League ",
    abbrev: "NPFL",
    country: "Nigeria",
    season: "2019/2020",
    teams: 20,
  },
  {
    club_name: "Egyptian Premier League",
    abbrev: "EPL",
    country: "Egypt",
    season: "2019/2020",
    teams: 18,
  },
  {
    club_name: "Tunisian Ligue Professionnelle 1",
    abbrev: "TLP1",
    country: "Tunisia",
    season: "2019/2020",
    teams: 20,
  },
  {
    club_name: "Algerian Ligue Professionnelle 1",
    abbrev: "ALP1",
    country: "Algeria",
    season: "2019/2020",
    teams: 16,
  },
  {
    club_name: "Ghana Premier League",
    abbrev: "GPL",
    country: "Ghana",
    season: "2019/2020",
    teams: 20,
  },
  {
    club_name: "Botola Pro 1",
    abbrev: "BP1",
    country: "Morocco",
    season: "2019/2020",
    teams: 16,
  },
  {
    club_name: "Sudan Premier League",
    abbrev: "SPL",
    country: "Sudan",
    season: "2019/2020",
    teams: 17,
  },
  {
    club_name: "South African Premier Division",
    abbrev: "SAPD",
    country: "South African",
    season: "2019/2020",
    teams: 16,
  },
  {
    club_name: "Elite 1",
    abbrev: "E1",
    country: "Cameroon",
    season: "2019/2020",
    teams: 18,
  },
];