export default [
  {
    league: "Nigeria Professional Premier League",
    home: "Eyimba FC",
    away: "Kano Pillars FC",
    time: "14:00",
    stadium: "Eyimba Stadium, Aba",
    date: "15-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Kogi United FC",
    away: "Sunshine FC",
    time: "14:30",
    stadium: "Pride of Kogi Stadium, Kogi",
    date: "15-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Plateau Utd",
    away: "Lobi Stars",
    time: "14:30",
    stadium: "Plateau Stadium",
    date: "16-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Enugu",
    away: "Kano Pillars",
    time: "15:00",
    stadium: "Nsukka Stadium, Enugu",
    date: "16-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Ifeanyi Uba",
    away: "Dakkada",
    time: "15:00",
    stadium: "Ifeanyi Uba Stadium",
    home_score: 3,
    away_score: 1,
    date: "12-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Warri",
    away: "Nasarawa Utd",
    time: "15:30",
    stadium: "Delta state Stadium, Delta",
    home_score: 2,
    away_score: 2,
    date: "12-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Wikki",
    away: "Jigawa",
    time: "16:00",
    stadium: "Divine Multi-purpose Stadium, K...",
    home_score: 2,
    away_score: 4,
    date: "12-09-2020",
  },
  {
    league: "Nigeria Professional Premier League",
    home: "Kwara Utd",
    away: "Adamawa Utd",
    time: "17:30",
    stadium: "Kwara state Stadium, Kwara",
    home_score: 1,
    away_score: 1,
    date: "12-09-2020",
  },
];