export default [
  {
    id: 1,
    teams: [],
    name: "Musa Ibafo",
    position: "goalkeeper",
    number: 1,
    playerMatchEvents: [],
  },
  {
    id: 2,
    teams: [],
    name: "Iwu Winifred",
    position: "goalkeeper",
    number: 12,
    playerMatchEvents: [],
  },
  {
    id: 3,
    teams: [],
    name: "Alicho Madu",
    position: "defender",
    number: 5,
    playerMatchEvents: [],
  },
  {
    id: 4,
    teams: [],
    name: "OluwaFeni Daniel",
    position: "forward",
    number: 11,
    playerMatchEvents: [],
  },
  {
    id: 5,
    teams: [],
    name: "Apkan Mba",
    position: "defender",
    number: 23,
    playerMatchEvents: [],
  },
  {
    id: 6,
    teams: [],
    name: "Fashina Adewunmi",
    position: "defender",
    number: 2,
    playerMatchEvents: [],
  },
  {
    id: 7,
    teams: [],
    name: "Lincoln Ani",
    position: "forward",
    number: 10,
    playerMatchEvents: [],
  },
  {
    id: 8,
    teams: [],
    name: "OluwaFeni Micheal",
    position: "midfielder",
    number: 8,
    playerMatchEvents: [],
  },
  {
    id: 9,
    teams: [],
    name: "Temi Collins",
    position: "forward",
    number: 20,
    playerMatchEvents: [],
  },
  {
    id: 10,
    teams: [],
    name: "Temi Collins",
    position: "midfielder",
    number: 4,
    playerMatchEvents: [],
  },
  {
    id: 1,
    teams: [],
    name: "Musa Ibafo",
    position: "goalkeeper",
    number: 1,
    playerMatchEvents: [],
  },
  {
    id: 2,
    teams: [],
    name: "Iwu Winifred",
    position: "goalkeeper",
    number: 12,
    playerMatchEvents: [],
  },
  {
    id: 3,
    teams: [],
    name: "Alicho Madu",
    position: "defender",
    number: 5,
    playerMatchEvents: [],
  },
  {
    id: 4,
    teams: [],
    name: "OluwaFeni Daniel",
    position: "forward",
    number: 11,
    playerMatchEvents: [],
  },
  {
    id: 5,
    teams: [],
    name: "Apkan Mba",
    position: "defender",
    number: 23,
    playerMatchEvents: [],
  },
  {
    id: 6,
    teams: [],
    name: "Fashina Adewunmi",
    position: "defender",
    number: 2,
    playerMatchEvents: [],
  },
  {
    id: 7,
    teams: [],
    name: "Lincoln Ani",
    position: "forward",
    number: 10,
    playerMatchEvents: [],
  },
  {
    id: 8,
    teams: [],
    name: "OluwaFeni Micheal",
    position: "midfielder",
    number: 8,
    playerMatchEvents: [],
  },
  {
    id: 9,
    teams: [],
    name: "Temi Collins",
    position: "forward",
    number: 20,
    playerMatchEvents: [],
  },
  {
    id: 10,
    teams: [],
    name: "Temi Collins",
    position: "midfielder",
    number: 4,
    playerMatchEvents: [],
  },
  {
    id: 9,
    teams: [],
    name: "Temi Collins",
    position: "forward",
    number: 20,
    playerMatchEvents: [],
  },
  {
    id: 10,
    teams: [],
    name: "Temi Collins",
    position: "midfielder",
    number: 4,
    playerMatchEvents: [],
  },
];
