export default [
  {
    id: 1,
    teams: [],
    name: "Musa Ibafo",
    position: "goalkeeper",
    number: 1,
    playerMatchEvents: [],
  },
  {
    id: 2,
    teams: [],
    name: "Iwu Winifred",
    position: "goalkeeper",
    number: 12,
    playerMatchEvents: [],
  },
  {
    id: 3,
    teams: [],
    name: "Alicho Madu",
    position: "defender",
    number: 5,
    playerMatchEvents: [],
  },
  {
    id: 4,
    teams: [],
    name: "George Apkan",
    position: "forward",
    number: 19,
    playerMatchEvents: [],
  },
  {
    id: 5,
    teams: [],
    name: "Ahmed Damilola",
    position: "defender",
    number: 6,
    playerMatchEvents: [],
  },
  {
    id: 6,
    teams: [],
    name: "Fashina Adewunmi",
    position: "defender",
    number: 2,
    playerMatchEvents: [],
  },
  {
    id: 7,
    teams: [],
    name: "Lincoln Ani",
    position: "forward",
    number: 10,
    playerMatchEvents: [],
  },
  {
    id: 8,
    teams: [],
    name: "OluwaFeni Micheal",
    position: "midfielder",
    number: 8,
    playerMatchEvents: [],
  },
  {
    id: 9,
    teams: [],
    name: "Temi Collins",
    position: "forward",
    number: 20,
    playerMatchEvents: [],
  },
  {
    id: 10,
    teams: [],
    name: "Gbenga Fawas",
    position: "midfielder",
    number: 21,
    playerMatchEvents: [],
  },
  {
    id: 11,
    teams: [],
    name: "Inyang Joshua",
    position: "defender",
    number: 33,
    playerMatchEvents: [],
  },
  {
    id: 12,
    teams: [],
    name: "Iwu Wale",
    position: "forward",
    number: 22,
    playerMatchEvents: [],
  },
  {
    id: 13,
    teams: [],
    name: "Emeka Madu",
    position: "defender",
    number: 3,
    playerMatchEvents: [],
  },
  {
    id: 14,
    teams: [],
    name: "OluwaFeni Daniel",
    position: "forward",
    number: 11,
    playerMatchEvents: [],
  },
  {
    id: 15,
    teams: [],
    name: "Apkan Mba",
    position: "defender",
    number: 23,
    playerMatchEvents: [],
  },
  {
    id: 16,
    teams: [],
    name: "Dan Fola",
    position: "defender",
    number: 28,
    playerMatchEvents: [],
  },
  {
    id: 17,
    teams: [],
    name: "Chima Eze",
    position: "forward",
    number: 14,
    playerMatchEvents: [],
  },
  {
    id: 18,
    teams: [],
    name: "Oba Temi",
    position: "midfielder",
    number: 18,
    playerMatchEvents: [],
  },
  {
    id: 19,
    teams: [],
    name: "Temi Collins",
    position: "forward",
    number: 20,
    playerMatchEvents: [],
  },
  {
    id: 20,
    teams: [],
    name: "Temi Collins",
    position: "midfielder",
    number: 4,
    playerMatchEvents: [],
  },
  {
    id: 21,
    teams: [],
    name: "Pami Eden",
    position: "goalkeeper",
    number: 40,
    playerMatchEvents: [],
  },
  {
    id: 22,
    teams: [],
    name: "Evans Raphael",
    position: "midfielder",
    number: 13,
    playerMatchEvents: [],
  },
];
