export default [
  {
    id: 1,
    team_name: "Eyimba FC",
    league: "NPFL",
    country: "Nigeria",
    players: 24,
  },
  {
    id: 2,
    team_name: "Kano pillars FC",
    league: "NPFL",
    country: "Nigeria",
    players: 23,
  },
  {
    id: 3,
    team_name: "Accra Hearts FC",
    league: "GFPL",
    country: "Ghana",
    players: 20,
  },
  {
    id: 4,
    team_name: "Eyimba FC",
    league: "NPFL",
    country: "Nigeria",
    players: 21,
  },
  {
    id: 5,
    team_name: "Kano pillars FC",
    league: "NPFL",
    country: "Nigeria",
    players: 26,
  },
  {
    id: 6,
    team_name: "Accra Hearts FC",
    league: "GFPL",
    country: "Ghana",
    players: 23,
  },
  {
    id: 7,
    team_name: "Eyimba FC",
    league: "NPFL",
    country: "Nigeria",
    players: 23,
  },
  {
    id: 8,
    team_name: "Kano pillars FC",
    league: "NPFL",
    country: "Nigeria",
    players: 20,
  },
  {
    id: 9,
    team_name: "Accra Hearts FC",
    league: "GFPL",
    country: "Ghana",
    players: 29,
  },
  {
    id: 10,
    team_name: "Eyimba FC",
    league: "NPFL",
    country: "Nigeria",
    players: 19,
  },
  {
    id: 11,
    team_name: "Kano pillars FC",
    league: "NPFL",
    country: "Nigeria",
    players: 33,
  },
  {
    id: 12,
    team_name: "Accra Hearts FC",
    league: "GFPL",
    country: "Ghana",
    players: 22,
  },
];