const COMPETITION = {
  FETCH_ALL: "FETCH_ALL",
  FETCH_ALL_SUCCESS: "FETCH_ALL_SUCCESS",
  ADD_COMPETITION: "ADD_COMPETITION",
};

const TEAM = {
  FETCH_TEAMS: "FETCH_TEAMS",
  FETCH_TEAMS_SUCCESS: "FETCH_TEAMS_SUCCESS",
  VIEW_TEAM: "VIEW_TEAM",
  ADD_TEAM: "ADD_TEAM",
};

const MATCH = {
  ADD_MATCH: "ADD_MATCH",
  FETCH_MATCHES: "FETCH_MATCHES",
  FETCH_MATCHES_SUCCESS: "FETCH_MATCHES_SUCCESS"
};

const AUTH = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_UNSUCCESSFUL: "LOGIN_UNSUCCESSFUL"
}

export { COMPETITION, TEAM, MATCH, AUTH };
